pontusab/directories

src/data/index.ts

This was based on the TypeScript template. I asked Claude 3.5 Sonnet to adapt it, and then I made some manual tweaks. It looks sensible, but I haven't used it in anger.

Add Ruby on Rails rules

---

package-lock.json
src/data/index.ts
src/data/rules/vue.ts

Add basic rules for Vue.js and its ecosystem.

feat: add Vue

---

src/data/index.ts
src/data/rules/react-native.ts

Add some best practices and rules for a React Native project using TypeScript and Expo. I sourced from official React Native and Expo docs. Love this project!

Add React Native cursor rules.

---

src/data/index.ts
src/data/rules/expo.ts

This PR introduces a detailed set of rules and best practices for developing production-grade Expo React Native applications using TypeScript. The guidelines cover various aspects of app development, ensuring consistency, performance optimization, and alignment with industry standards.
- Adopted functional and declarative programming patterns.
- Emphasized modularization over code duplication.
- Defined clear naming conventions and file structure best practices.
- Enforced strict TypeScript with a preference for interfaces over types.
- Avoided the use of enums; promoted the use of maps instead.
- Encouraged the use of functional components with TypeScript interfaces.
- Leveraged Expo's built-in components and responsive design using Flexbox.
- Introduced the use of `SafeAreaView`, …

Add comprehensive Expo React Native TypeScript development rule for cursor

---

src/data/index.ts
src/data/rules/data-analyst.ts

add Data Analyst Jupyter Notebook rules

add Data Analyst Jupyter Notebook rules

---

src/data/index.ts
src/data/rules/julia.ts

This PR adds my cursorrules for Julia language. I use it for data science projects but most of it is general enough for any Julia project

Add JuliaLang rules for data science

---

src/components/product-hunt.tsx
src/components/rule-card.tsx

This PR includes minor ui improvements.
<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<body>
<tr>
<td><img src="https://github.com/user-attachments/assets/6d0bffa8-3b24-407d-abe7-89b4503276d4" alt="Before" /></td>
<td><img src="https://github.com/user-attachments/assets/7ec077ef-8fbc-4153-bad2-45f964a9406a" alt="After" /></td>
</tr>
</tbody>
</table>

Minor ui improvements

---

src/data/rules/nextjs.ts

This PR adds a new guide titled "Next.js React Generalist Cursor Rules" to the repository. The guide outlines best practices for making suggestions and implementing changes in Next.js and React projects. It emphasizes clarity, security, and operational soundness, providing a framework for producing high-quality, maintainable code.

Add new (generalist) rule for Next.js

---

src/data/rules/expo.ts

This PR updates the Expo React Native JavaScript Best Practices section in the expo.ts file to include a concise summary of Expo Router. The update:
1. Recommends using Expo Router for file-based routing in React Native apps
2. Highlights key features: native navigation, deep linking, and cross-platform support
3. Useful for developers building and maintaining aopps that are in pure javascript

Add new Rules for Pure Javascript and Expo

---

src/data/index.ts
src/data/rules/deep-learning.ts

This PR updates the `deepLearningRules` configuration to include detailed guidelines for deep learning development, focusing on PyTorch, Transformers, Diffusers, and Gradio libraries. The content provides a comprehensive set of principles, best practices, and conventions for efficient and effective deep learning workflows.
- Added key principles for writing concise, technical responses with accurate Python examples.
- Detailed the use of PyTorch for deep learning tasks, including custom model architectures, weight initialization, and normalization techniques.
- Explained the implementation of Transformers and LLMs, emphasizing attention mechanisms, positional encodings, and efficient fine-tuning techniques.
- Described the use of Diffusers library for diffusion models, including forward …

[feat](data/rules) Add new Rules for Deep Learning Developer

---

src/data/rules/react-native.ts

Cursor rules for react three fiber, threejs, react, tailwind css

react, threejs, r3f, tailwind

---

src/data/index.ts
src/data/rules/nestjs.ts

Add NestJS rules to write clean APIs with Cursor

---

src/data/rules/angular.ts

feat: angular rules

---

src/data/index.ts
src/data/rules/flutter.ts

Flutter cursor rules

---

src/data/index.ts
src/data/rules/angular.ts
src/data/rules/gastby.ts

- Add rules for Gatsby
- Remove uppercase on `Angular` for consistency sake

feat: 🎸 add gatsby rules

---

src/data/rules/nextjs.ts

:bug: Fixed issue with copied slugs

---

src/data/index.ts
src/data/rules/rust.ts

This is the rules I am using to write Rust.

feat: add rust rules

---

src/data/index.ts
src/data/rules/uiux-design.ts

new category: UX and UI Design

submitting a new category and rule

---

src/app/api/popular/route.ts

Fix: Popular API endpoint returns duplicated data (#68)

---

src/data/videos.ts

Added new video: [Youtube](https://youtu.be/nUTR11D8q08?si=ChSROaC1fM7BGh40)

Added new video

---

src/data/index.ts
src/data/rules/java.ts

Add a rule for java cursor rule which includes spring boot

Java cursor rule

---

src/data/index.ts
src/data/rules/salesforce.ts

I added a prompt to support the common use case for IDE development in the Salesforce Platform: custom frontend and backend code.

added a Salesforce development prompt.

---

src/data/rules/wordpress.ts

Added a simple WordPress development prompt

added a simple WordPress development prompt

---

README.md

- Expanded step-by-step guide for submitting new rules.
- Clear instructions on adding new prompts to existing rules.
- Important parameters for rule files, including:
- tags, title, slug, and content for better structure and author details.

Update contribution guide for rule submissions.

---

src/data/index.ts
src/data/rules/wordpress-woocommerce.ts

New rule for WordPress and WooCommerce

WordPress & WooCommerce

---

src/data/index.ts
src/data/rules/blazor.ts

Add optimized Blazor-specific rules that help cursor understand the codebase is Blazor and the testing needs to be done on Visual Studio.

Add Blazor-specific development rules

---

README.md
src/data/rules/wordpress.ts

Rules for WordPress
- Implemented a comprehensive set of rules and guidelines for WordPress projects.
- Includes PHP and WordPress coding standards, file structure, error handling, and security best practices.
- Added support for modular code with hooks, OOP, and proper data sanitization.
- Enhanced rules for asset management, theme development, and database operations.
- Focused on improving code consistency, maintainability, and efficiency.
Update the readme file.

Add WordPress Development Best Practices to Cursor AI Rules Directory

---

src/data/index.ts
src/data/rules/jax.ts

JAX Best Practices rule

---

src/data/index.ts
src/data/rules/autohotkey.ts

Provides rules for the AutoHotkey automating language

Autohotkey Rules

---

src/data/rules/laravel.ts

This pull request introduces a comprehensive set of rules and best practices for using Laravel with the Tall Stack, focusing on component-based architecture, Eloquent ORM usage, and integration with TailwindCSS and Livewire for enhanced UI development.

Add new TALL stack Cursor Rules for Laravel, Livewire, Alpine.js, TailwindCSS, and DaisyUI

---

src/data/index.ts
src/data/rules/onchainkit.ts

OnchainKit is a comprehensive toolkit designed to simplify the process of building beautiful onchain applications for web developers. It provides a set of React components and utilities that make it easy to integrate blockchain functionality into web applications, particularly those built with React.
**Key features of OnchainKit include:**
- Easy integration with existing projects
- Pre-styled components for quick implementation
- Support for identity management (ENS avatars, attestation badges, etc.)
- Wallet connection and management
- The project aims to lower the barrier of entry for developers looking to build blockchain-enabled web applications, providing a set of easy-to-use components and utilities that handle complex blockchain interactions. We currently have 10k+ weekly npm …

Add "OnchainKit" rules

---

src/data/rules/laravel.ts

Laravel & PHP guidelines from [https://spatie.be/guidelines/laravel-php](https://spatie.be/guidelines/laravel-php)

New cursor rule for Laravel & PHP

---

src/data/index.ts
src/data/rules/android.ts

added android rules to the cursor directory

Amansatija patch 1- added android rules

---

src/data/index.ts
src/data/rules/ghost-tailwindcss.ts
yarn.lock

Add my development ghost CMS with Tailwindcss and Alpinejs lib

Add ghost CMS with Tailwindcss and Alpinejs theming rule

---

pnpm-lock.yaml
src/data/index.ts
src/data/rules/devops-backend.ts
yarn.lock

imported devops rule in index.js
prompts for bash, azure pipeline and ansible added

Added devops rules

---

src/data/index.ts
src/data/rules/cpp.ts

This pull request introduces comprehensive development guidelines for modern C++ programming, providing a structured reference for best practices and coding standards.
Covers essential aspects of C++ development, including syntax, performance, security, and architectural considerations.
> Refers to Issue number #17

Cpp development rules

---

src/data/rules/java.ts

Expanding java's cursor rule for the quarkus.io framework

Expanding java's rules on quarkus.io 

---

src/data/index.ts
src/data/rules/webScraping.ts

Web scraping ruleset that contains modern tools has added.

Web Scraping Ruleset

---

src/data/rules/flutter.ts

A small contribution to Flutter with other libraries

Add new Flutter rules

---

src/data/index.ts
src/data/rules/angular-ionic-firebase-firestore.ts
src/data/rules/cpp.ts
src/data/rules/fastify.ts
src/data/rules/typescript.ts

Typescript Cursor rules with 'shortcuts' to use within prompts; Opinionated to use Lodash & Zod

add general typescript rules

---

src/data/videos.ts

✨ New Video: "Master Cursor Rules and Fix AI Code Mistakes—Here’s How"

Update videos.ts – Added cursorrule video

---

packages/data/src/mcp/index.ts

- Adds the official Firecrawl MCP server
Thank you!

Add Firecrawl MCP Server

---

packages/data/src/rules/elixir.ts

I've created a new rule for Elixir / Phoenix based on PragDave (Dave Thomas') programming philosophy.

Added a new elixir rule

---

packages/data/src/mcp/index.ts

This PR adds the JSON Resume MCP Server to the MCP server directory. The JSON Resume MCP Server enhances AI assistants by enabling them to analyze a developer's codebase and automatically update their JSON Resume with relevant project details and skills.  
- **Resume Enhancement** – Automatically analyzes the user's codebase and adds project details to their JSON Resume.  
- **GitHub Integration** – Fetches and updates resumes stored in GitHub Gists.  
- **AI-Powered** – Uses OpenAI to generate professional descriptions of projects and technical skills.  
- **TypeScript/Zod Validation** – Ensures JSON Resume compliance.  
- **JSON Resume Ecosystem Compatibility** – Works seamlessly with the JSON Resume registry.

Added JSON Resume MCP server

---

packages/data/src/mcp/index.ts

This adds an MCP server for GCP to interact with your gcp resources easily using natural language

chore: Add mcp server for GCP

---

packages/data/src/rules/index.ts
packages/data/src/rules/viewcomfy.ts

Added the Python rule used by our users to help with our API integration. 
ViewComfy is a set of tools for deploying ComfyUI (image and video generation) workflows as serverless APIs. (https://www.viewcomfy.com/)

added ViewComfy rule

---

packages/data/src/rules/index.ts
packages/data/src/rules/rspec.ts

This PR introduces a comprehensive set of RSpec testing best practices guidelines to the project. The guidelines provide developers with clear standards for creating effective, maintainable tests, including:
1. **Comprehensive test coverage** for typical and edge cases
2. **Readability and clarity** guidelines for describe/context blocks and assertions
3. **Logical test structure** with proper organization using describe/context and subject
4. **Test data management** best practices using let/let! and factories
5. **Independence and isolation** techniques, with guidance on proper use of mocks and stubs
6. **DRY principles** for test code through shared examples and helpers
7. **File structure conventions** that mirror implementation paths within the spec directory

Add RSpec rules

---

packages/data/src/rules/cloudflare.ts

based on https://developers.cloudflare.com/workers/prompt.txt

Cloudflare rules

---

packages/data/src/rules/rails-api.ts

Adds a detailed set of best practices and conventions for building robust Ruby on Rails APIs. These rules cover key areas including code quality, API design, controller logic, error handling, data management, security, performance, testing, and documentation.
Key features of this ruleset include:
- Emphasis on Rails conventions and idiomatic Ruby.
- Guidelines for skinny controllers, service objects, and query objects.
- Strong focus on centralized exception handling using `rescue_from` to map errors to standardized JSON responses and HTTP status codes.
- Best practices for security (auth, CORS, rate limiting, strong params).
- Performance optimization techniques (N+1 prevention, caching, indexing).
- Importance of request specs for testing API behavior.
- Requirements for clear API …

Define Rails API cursor guidelines and rules

---

packages/data/src/rules/flutter.ts

This PR adds a new rule to Directories for Flutter that implements:
- Clean Architecture with proper layer separation
- Feature-first organization for directory structure
- State management using flutter_bloc
- Functional error handling with Dartz package
The new rule provides detailed guidance on:
- Clean Architecture principles applied to Flutter
- Directory structure organized by features
- Implementation of Blocs and Cubits for state management
- Dependency injection using GetIt
- Functional error handling pattern with Either<Failure, Success>
- Code examples for Use Cases, Repositories, Blocs, and UI
- Coding best practices and testing strategies
- Verified correct syntax in the TS file
- Rule content is well-structured and properly formatted

Add new rule for Flutter + Clean Architecture + Feature-first + flutter_bloc

---

packages/data/src/rules/index.ts
packages/data/src/rules/playwright.ts

Add Playwright Testing Rules for enhanced testing and automation interaction.

Add Playwright Rules

---

packages/data/src/rules/drupal.ts
packages/data/src/rules/index.ts

Added cursor rules for the [Drupal](https://new.drupal.org/home) CMS.

Added Drupal rule.

---

packages/data/src/rules/index.ts
packages/data/src/rules/odoo.ts

Added feature: Odoo/Python Cursor Rules
Key Principles
- Expertise & Clarity: Write clear, technical responses with precise Odoo examples and code snippets that demonstrate best practices.
- Modular Design: Leverage Odoo’s module-based architecture to separate business logic, data models, views, and controllers.
- Readability & Maintainability: Follow PEP 8 guidelines for Python code, and adhere to Odoo’s recommended coding styles. Use descriptive names for models, fields, methods, and XML nodes.
- Leverage Built-in Features: Make full use of Odoo’s built-in ORM, API decorators, XML view inheritance, and security frameworks to minimize boilerplate code and maximize integration.

Added feature: Odoo Cursor Rules

---

src/data/rules/cairo.ts

Adds rules for programming Cairo 1.0 contracts for Starknet

Add rules for Cairo 1.0

---

src/data/rules/symfony.ts

add Symfony development guidelines and best practices
- Add comprehensive Symfony development rules and standards
- Include core principles and dependencies
- Document code architecture patterns and conventions
- Add detailed sections for security, testing, and performance
- Include practical examples for Controllers, Entities, and Services

add Symfony development guidelines and best practices

---

packages/data/src/rules/django.ts

New rule added to rules/Django.ts :)

Add Django REST API Development Rule

---

packages/data/src/rules/index.ts
packages/data/src/rules/manifest.ts

New rule added for [Manifest backend](https://manifest.build)

feat: Add Manifest Cursor rules
